languageCode = "en-us"
title = "midlang website"
baseurl = "http://midlang.org/"
theme = "hugo-material-docs"
metadataformat = "yaml"
pygmentsUseClasses = true
canonifyurls = true

[params]
	author = "mkideal"
	description = "midlang website"
	copyright = "midlang"

	provider = "GitHub"
	repo_url = "https://github.com/midlang/mid"
	repo_id = "mid"

[social]
	github = "mkideal"
	twitter = "mkideal"
	email = "i@mkideal.com"

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 0

[[menu.main]]
	name = "Download"
	url = "dl/"
	weight = 10

[blackfriday]
	smartypants = true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
